### ISSUE TITLE
Change readme to the current github address

### ISSUE THREAD

**Issue by mediapathic** [DivineDominion/criticmarkup.tmbundle#7]
Right now the readme instructions include `git clone git://github.com...`. This is apparently no longer supported by github, and should probably be `git clone https://github.com...`

(see, someone still cares! :) )

**Comment by DivineDominion** [comment]
Didn't remember the project, thanks! :) 

If you happen to know the URL that works, could you provide a PR that does the trick? (I'm too far gone ... you know where)

**Comment by mediapathic** [comment]
PR made! Thanks for the exercise in remembering how to make a PR. :)

**Comment by DivineDominion** [comment]
Happy to help! :)
